// Copyright 2022 Team Havtorn. All Rights Reserved.

#pragma once

#include "ECS/Entity.h"
#include "ECS/Component.h"
#include "ECS/System.h"

#include "ECS/Systems/RenderSystem.h"
#include "ECS/Systems/CameraSystem.h"
#include "ECS/Systems/LightSystem.h"
#include "ECS/Systems/AnimatorGraphSystem.h"
#include "ECS/Systems/SpriteAnimatorGraphSystem.h"
#include "ECS/Systems/SequencerSystem.h"
#include "../HexPhys/HexPhys.h"
#include "../HexAudio/HexAudio.h"
#include "ECS/Systems/ScriptSystem.h"
#include "ECS/Systems/UISystem.h"
#include "ECS/Systems/LevelStreamingSystem.h"
#include "ECS/Systems/AbilitySystem.h"
#include "ECS/Systems/InputSystem.h"

#include "ECS/Components/TransformComponent.h"
#include "ECS/Components/StaticMeshComponent.h"
#include "ECS/Components/SkeletalMeshComponent.h"
#include "ECS/Components/SkeletalAnimationComponent.h"
#include "ECS/Components/CameraComponent.h"
#include "ECS/Components/CameraControllerComponent.h"
#include "ECS/Components/InputComponent.h"
#include "ECS/Components/MaterialComponent.h"
#include "ECS/Components/EnvironmentLightComponent.h"
#include "ECS/Components/DirectionalLightComponent.h"
#include "ECS/Components/PointLightComponent.h"
#include "ECS/Components/PrefabComponent.h"
#include "ECS/Components/SpotLightComponent.h"
#include "ECS/Components/VolumetricLightComponent.h"
#include "ECS/Components/DecalComponent.h"
#include "ECS/Components/SpriteComponent.h"
#include "ECS/Components/Transform2DComponent.h"
#include "ECS/Components/SpriteAnimatorGraphComponent.h"
#include "ECS/Components/SequencerComponent.h"
#include "ECS/Components/ScriptComponent.h"
#include "ECS/Components/Physics2DComponent.h"
#include "ECS/Components/Physics3DComponent.h"
#include "ECS/Components/Physics3DControllerComponent.h"
#include "ECS/Components/UICanvasComponent.h"
#include "ECS/Components/LevelStreamingComponent.h"
#include "ECS/Components/AbilityComponent.h"
#include "ECS/Components/AudioEmitterComponent.h"
#include "ECS/Components/AudioListenerComponent.h"
#include "ECS/Components/DebugShapeComponent.h"
#include "ECS/Components/MetaDataComponent.h"

#include "Hex/HexCommandComponent.h"
